[server]
headless = true
port = 8080
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8080

[runner]
fastReruns = false

[client]
showErrorDetails = false
toolbarMode = "minimal"
