[server]
headless = true
port = 8501
address = "localhost"
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[runner]
fastReruns = false

[client]
showErrorDetails = false
toolbarMode = "minimal"
